
package io.crud.gui;

import io.crud.dao.HistoricoPesoDAO;
import java.sql.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import io.crud.modelo.HistoricoPeso;
import io.crud.utils.DateConverter;

public class AlteracaoGUI extends javax.swing.JFrame {
    
    private AtualizacaoGUI telaAtualizacao; 
    
    public AlteracaoGUI(HistoricoPeso historicoPeso, AtualizacaoGUI telaAtualizacao) {
        
        this.telaAtualizacao = telaAtualizacao;
        
        setTitle("Gym: alterar registro");
        setSize(430,200);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(AlteracaoGUI.DISPOSE_ON_CLOSE);
               
        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/gym.png"));
        setIconImage(icon.getImage());
        
        initComponents();
        
        jTxtIdRegistro.setText(String.valueOf(historicoPeso.getId()));
        jTxtIdAluno.setText(String.valueOf(historicoPeso.getAlunoId()));
        jTxtDataRegistro.setText(historicoPeso.getDataRegistroFormatada());
        jTxtPeso.setText(String.valueOf(historicoPeso.getPeso()));
        
    }
    
    public AlteracaoGUI() {
        initComponents();   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnBackToAtualizacao = new javax.swing.JButton();
        jTxtDataRegistro = new javax.swing.JTextField();
        jLblDataRegistro = new javax.swing.JLabel();
        jLblIdRegistro = new javax.swing.JLabel();
        jTxtIdRegistro = new javax.swing.JTextField();
        jLblIdAluno = new javax.swing.JLabel();
        jTxtIdAluno = new javax.swing.JTextField();
        jLblPeso = new javax.swing.JLabel();
        jTxtPeso = new javax.swing.JTextField();
        jBtnAplicar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(420, 200));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBtnBackToAtualizacao.setText("Voltar para Atualização");
        jBtnBackToAtualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackToAtualizacaoActionPerformed(evt);
            }
        });

        jTxtDataRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDataRegistroActionPerformed(evt);
            }
        });

        jLblDataRegistro.setText("Data de Registro:");

        jLblIdRegistro.setText("Código Registro:");

        jTxtIdRegistro.setEditable(false);

        jLblIdAluno.setText("Código Aluno:");

        jTxtIdAluno.setEditable(false);

        jLblPeso.setText("Peso :");

        jBtnAplicar.setText("Aplicar Alteração");
        jBtnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnBackToAtualizacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnAplicar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblDataRegistro, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblIdRegistro, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTxtIdRegistro)
                            .addComponent(jTxtDataRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblIdAluno, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblPeso, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtIdAluno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtPeso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLblIdRegistro)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTxtIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLblPeso)
                                        .addComponent(jTxtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(jLblIdAluno)
                                    .addGap(43, 43, 43)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTxtIdRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLblDataRegistro)
                                    .addComponent(jTxtDataRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAplicar)
                    .addComponent(jBtnBackToAtualizacao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtDataRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDataRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDataRegistroActionPerformed

    private void jBtnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAplicarActionPerformed
    
        if ((jTxtDataRegistro.getText().isEmpty())) {
            JOptionPane.showMessageDialog(this, "O campo DATA DE REGISTRO nao pode retornar vazio");
        }
        else if ((jTxtPeso.getText().isEmpty())) {
            JOptionPane.showMessageDialog(this, "O campo PESO nao pode retornar vazio");
        }
        else {
            
            HistoricoPeso historicoPeso = new HistoricoPeso();   
            String formato = "dd/MM/yyyy";
            java.sql.Date data = DateConverter.transformToSqlDate(jTxtDataRegistro.getText(), formato);
            if(data == null){
                JOptionPane.showMessageDialog(this, "O campo DATA DE REGISTRO deve possuir o formato: " + formato);
            }
            else{
                try {
                    float peso = Float.parseFloat(jTxtPeso.getText());
                    
                    historicoPeso.setId(Integer.parseInt(jTxtIdRegistro.getText()));
                    historicoPeso.setAlunoId(Integer.parseInt(jTxtIdAluno.getText()));
                    historicoPeso.setDataRegistro(data);
                    historicoPeso.setPeso(peso);

                    HistoricoPesoDAO daoHistorico = new HistoricoPesoDAO();
                    daoHistorico.atualizar(historicoPeso);
                    JOptionPane.showMessageDialog(this, "Histórico alterado com sucesso!");
                    telaAtualizacao.atualizacaoDoHistorico();
                    
                }
                catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Verifique o campo PESO! Utilize ponto em vez de vírgula!");
                }
            }

        }  

    }//GEN-LAST:event_jBtnAplicarActionPerformed

    private void jBtnBackToAtualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackToAtualizacaoActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnBackToAtualizacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlteracaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlteracaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlteracaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlteracaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlteracaoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAplicar;
    private javax.swing.JButton jBtnBackToAtualizacao;
    private javax.swing.JLabel jLblDataRegistro;
    private javax.swing.JLabel jLblIdAluno;
    private javax.swing.JLabel jLblIdRegistro;
    private javax.swing.JLabel jLblPeso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtDataRegistro;
    private javax.swing.JTextField jTxtIdAluno;
    private javax.swing.JTextField jTxtIdRegistro;
    private javax.swing.JTextField jTxtPeso;
    // End of variables declaration//GEN-END:variables
}
